### ISSUE TITLE
Sponsored ad got through on 1.9.3 in Chrome

### ISSUE THREAD

**Issue by pa28236** [siradar/facebook_adblock#95]
All was good, then I just saw this Sponsored ad. Running 1.9.3 in Chrome. Still, better than it was in 1.9.2 for me.
Now...to get rid of all the "Suggested for You" ads!

![image](https://user-images.githubusercontent.com/61201326/116105791-a852fb00-a67f-11eb-9a67-190f43d8e40b.png)

**Comment by tiratatp** [comment]
I think this is because I forgot to include #89 in 1.9.3.

You only see political ads like this right?

**Comment by dfayruzov** [comment]
I'm waiting for get rid of "suggsted for you" ads too. 
In the meanwhile: switching to Most Recent tab restores "sponsored" ads (and yes, they are NOT political ads). 

First time here - if it's needed, just tell me - I'll reopen as new bug.
![image](https://user-images.githubusercontent.com/28098650/116196538-502dfe80-a73c-11eb-8d2f-d0c65899a8e7.png)

**Comment by jmccl** [comment]
I'm also getting sponsored (non-political) ads on Chrome Version 90.0.4430.85 

![Screenshot_2021-04-28_08-36-31](https://user-images.githubusercontent.com/5283750/116431824-fb05f180-a7fc-11eb-8a76-26b6378259aa.png)

**Comment by SanskritFritz** [comment]
Same problem on Firefox, version 1.9.3

![Screenshot_20210520_170520](https://user-images.githubusercontent.com/209814/119003515-12647480-b98e-11eb-8f6a-126852d98755.jpg)

**Comment by offroadpaparazzi** [comment]
seeing this in facebook.com/watch ( ad every 5th post)

![watch](https://user-images.githubusercontent.com/60391279/119574292-81254180-bd83-11eb-8fea-b28a612ab9cc.JPG)

**Comment by HaiDang666** [comment]
<img width="981" alt="Screen Shot 2021-05-28 at 11 59 26" src="https://user-images.githubusercontent.com/12780733/119931798-43573180-bfac-11eb-83bc-34963c48595d.png">

- fb.com: still works in FireFox (88.0.1 - 64bit)
- fb.com/watch: not work

**Comment by tiratatp** [comment]
Looking. I'll work on this tomorrow.

**Comment by tiratatp** [comment]
I think the problem is when you change page to the news feed.

I could see the extension is detecting this and monitor a new container.

But it does not seem to find ad elements, even though it is still using `a[aria-label="Sponsored"]`.

@cbotsikas do you have a clue of what this could be?

**Comment by tiratatp** [comment]
Hi @pa28236 can you test this for me? Would the ads go away if you refresh your page?

There might be a race condition when changing page; by refreshing a page, you trigger our code to scan the page again.

**Comment by cbotsikas** [comment]
@tiratatp found the issue... observers were cleaned up but the dom elements were not replaced anymore, so our dataset attributes were not cleaned.

**Comment by tiratatp** [comment]
@cbotsikas You rock!

**Comment by cbotsikas** [comment]
For the record, for some reason which I don't want to search, I was not able to reproduce the problem with the console open !?

**Comment by offroadpaparazzi** [comment]
I can’t reproduce this at all

 

Hmmmm

 

Thank You for all you do.

 

-art

 

 

From: Christos Botsikas ***@***.***>
Reply-To: siradar/facebook_adblock ***@***.***>
Date: Wednesday, June 23, 2021 at 6:34 PM
To: siradar/facebook_adblock ***@***.***>
Cc: ***@***.***" ***@***.***>, Comment ***@***.***>
Subject: Re: [siradar/facebook_adblock] Sponsored ad got through on 1.9.3 in Chrome (#95)

 

For the record, for some reason which I don't want to search, I was not able to reproduce the problem with the console open !?

**Comment by tiratatp** [comment]
You can update to 1.9.4 for Firefox now. But for Chrome, it is in review.

**Comment by offroadpaparazzi** [comment]
Thank You
