### ISSUE TITLE
Problem with "proposition for you"

### ISSUE THREAD

**Issue by PanPeople** [siradar/facebook_adblock#96]
**Environment**
Chrome

**Describe the bug**
Sorry but i can't make it as suggestion 
But i have problem with this annoying posts:
![image](https://user-images.githubusercontent.com/30329682/119901596-651dcd80-bf46-11eb-99af-9a424fe3033e.png)

Maybe you can get rid of this things?

Thanks for your awesome work

**Comment by tiratatp** [comment]
Duplicated of #62
